{
  "networks": {
    "slacksnet": {
      "driver": "bridge"
    }
  },
  "services": {
    "slacksdb": {
        "image": "postgres",
        "restart": "always",
        "environment": 
        "volumes"
    },
    "slacksdb": {
      "container_name": "slacksdb",
      "environment": {"POSTGRES_PASSWORD": "password"},
      "expose": ["5432"],
      "image": "postgres",
      "networks": ["slacksnet"],
      "ports": ["5432:5432"],
      "restart": "always",
      "volumes": [
        "./db:/var/lib/postgresql/data/",
      ]
    }
  },
  "version": "3"
}
